### ISSUE TITLE
use a common "figures" directory

### ISSUE THREAD

**Issue by topepo** [tidymodels/workshops#121]
In each qmd file's yaml: 

```yml
knitr:
  opts_chunk: 
    echo: true
    collapse: true
    comment: "#>"
    fig.path: "figures/"
```
